version: '3.8'
networks:
  vulnnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/15
services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    networks:
      vulnnet:
        ipv4_address: 172.30.1.1
    tty: true
    stdin_open: true
    command: /bin/bash -c "/etc/init.d/networking start && /etc/init.d/xinetd start
      && /etc/init.d/apache2 start && /etc/init.d/ssh start && /etc/init.d/mysql start
      && /etc/init.d/postgresql-8.3 start && /etc/init.d/samba start && sleep
      infinity"


  proftpd-vuln:
    image: infosecwarrior/ftp:v1
    container_name: proftpd-vuln
    networks:
      vulnnet:
        ipv4_address: 172.30.2.2
    ports:
    - '127.0.0.1:2122:21'
  ssh-cve-2016-6515:
    image: vulnerables/cve-2016-6515
    container_name: ssh-vuln-dos
    networks:
      vulnnet:
        ipv4_address: 172.30.3.1
    ports:
    - '127.0.0.1:2222:22'
  ubuntu-sshd-old:
    image: rastasheep/ubuntu-sshd:14.04
    container_name: ubuntu-ssh-old
    networks:
      vulnnet:
        ipv4_address: 172.30.3.2
    ports:
    - '127.0.0.1:2223:22'
  sambacry:
    image: vulnerables/cve-2017-7494
    container_name: sambacry
    networks:
      vulnnet:
        ipv4_address: 172.30.4.1
    ports:
      - 127.0.0.1:4451:445
      - 127.0.0.1:1391:139
  dns-vuln:
    image: infosecwarrior/dns-lab:v2
    container_name: dns-vuln
    networks:
      vulnnet:
        ipv4_address: 172.30.5.1
    ports:
      - 127.0.0.1:5353:53/udp
      - 127.0.0.1:8053:80
  apache-cve-2021-41773:
    image: httpd:2.4.49
    container_name: apache-path-traversal
    networks:
      vulnnet:
        ipv4_address: 172.30.6.3
    ports:
      - 127.0.0.1:8882:80
  log4shell:
    image: ghcr.io/christophetd/log4shell-vulnerable-app
    container_name: log4shell
    networks:
      vulnnet:
        ipv4_address: 172.30.6.4
    ports:
      - 127.0.0.1:8883:8080

  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    networks:
      vulnnet:
        ipv4_address: 172.30.7.1
    ports:
      - 127.0.0.1:3000:3000
  hackazon:
    image: ianwijaya/hackazon
    container_name: hackazon
    networks:
      vulnnet:
        ipv4_address: 172.30.7.2
    ports:
      - 127.0.0.1:8001:80

  webgoat:
    image: webgoat/webgoat
    container_name: webgoat
    networks:
      vulnnet:
        ipv4_address: 172.30.8.1
    ports:
      - 127.0.0.1:8003:8080
      - 127.0.0.1:9090:9090
    environment:
    - WEBGOAT_PORT=8080

  railsgoat:
    image: owasp/railsgoat
    container_name: railsgoat
    command: bash -c "bundle exec rails db:setup && bundle exec rails server -b 0.0.0.0 -p 3000"
    networks:
      vulnnet:
        ipv4_address: 172.30.8.3
    ports:
      - 127.0.0.1:3001:3000
  security-shepherd:
    image: ismisepaul/securityshepherd
    container_name: security-shepherd
    networks:
      vulnnet:
        ipv4_address: 172.30.8.4
    ports:
      - 127.0.0.1:8004:80
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    networks:
      vulnnet:
        ipv4_address: 172.30.9.1
    ports:
      - 127.0.0.1:8005:80
  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    networks:
      vulnnet:
        ipv4_address: 172.30.9.2
    ports:
      - 127.0.0.1:8006:80
  mutillidae:
    image: citizenstig/nowasp
    container_name: mutillidae
    networks:
      vulnnet:
        ipv4_address: 172.30.9.3
    ports:
      - 127.0.0.1:8007:80


  webgoat-legacy:
    image: webgoat/webgoat
    container_name: webgoat-legacy
    networks:
      vulnnet:
        ipv4_address: 172.30.9.7
    ports:
      - 127.0.0.1:8011:8080

  vampi:
    image: erev0s/vampi
    container_name: vampi
    networks:
      vulnnet:
        ipv4_address: 172.30.10.2
    ports:
      - 127.0.0.1:5002:5000
  damn-vulnerable-graphql:
    image: dolevf/dvga
    container_name: dvga
    networks:
      vulnnet:
        ipv4_address: 172.30.10.4
    ports:
      - 127.0.0.1:5013:5013
  wordpress-vuln:
    image: wordpress:4.6
    container_name: wordpress-vuln
    networks:
      vulnnet:
        ipv4_address: 172.30.11.1
    ports:
      - 127.0.0.1:8015:80

  # gitlab-vuln:
  #   image: gitlab/gitlab-ce:10.0.0-ce.0
  #   container_name: gitlab-vuln
  #   networks:
  #     vulnnet:
  #       ipv4_address: 172.30.12.2
  #   ports:
  #     - 127.0.0.1:8017:80


  mysql-old:
    image: mysql:5.5
    container_name: mysql-old
    networks:
      vulnnet:
        ipv4_address: 172.30.14.1
    ports:
      - 127.0.0.1:33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
  postgres-old:
    image: postgres:9.4
    container_name: postgres-old
    networks:
      vulnnet:
        ipv4_address: 172.30.14.2
    ports:
      - 127.0.0.1:54321:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
  mongodb-noauth:
    image: mongo:3.4
    container_name: mongodb-noauth
    networks:
      vulnnet:
        ipv4_address: 172.30.14.3
    ports:
      - 127.0.0.1:27017:27017
  redis-noauth:
    image: redis:4.0
    container_name: redis-noauth
    networks:
      vulnnet:
        ipv4_address: 172.30.14.4
    ports:
      - 127.0.0.1:6382:6379
  elasticsearch-old:
    image: elasticsearch:2.4.6
    container_name: elasticsearch-old
    networks:
      vulnnet:
        ipv4_address: 172.30.14.5
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
    - discovery.type=single-node
  couchdb-old:
    image: couchdb:1.6
    container_name: couchdb-old
    networks:
      vulnnet:
        ipv4_address: 172.30.14.6
    ports:
      - 127.0.0.1:5984:5984
  nginx-old:
    image: nginx:1.10
    container_name: nginx-old
    networks:
      vulnnet:
        ipv4_address: 172.30.15.1
    ports:
      - 127.0.0.1:8020:80
  apache-old:
    image: httpd:2.2
    container_name: apache-old
    networks:
      vulnnet:
        ipv4_address: 172.30.15.2
    ports:
      - 127.0.0.1:8021:80
  lighttpd:
    ports:
      - 127.0.0.1:8055:80
    container_name: lighttpd
    image: sebp/lighttpd
    networks:
      vulnnet:
        ipv4_address: 172.31.1.14


  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    networks:
      vulnnet:
        ipv4_address: 172.30.17.1
    ports:
      - 127.0.0.1:1025:1025
      - 127.0.0.1:1080:1080
  squid-old:
    image: sameersbn/squid:3.3.8-23
    container_name: squid-old
    networks:
      vulnnet:
        ipv4_address: 172.30.18.1
    ports:
      - 127.0.0.1:3128:3128
  kibana-old:
    image: kibana:4.6
    container_name: kibana-old
    networks:
      vulnnet:
        ipv4_address: 172.30.19.1
    ports:
      - 127.0.0.1:5601:5601
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch-old:9200
  grafana-old:
    image: grafana/grafana:5.1.0
    container_name: grafana-old
    networks:
      vulnnet:
        ipv4_address: 172.30.19.2
    ports:
      - 127.0.0.1:3003:3000
  rabbitmq-old:
    image: rabbitmq:3.6-management
    container_name: rabbitmq-old
    networks:
      vulnnet:
        ipv4_address: 172.30.20.1
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
  activemq-old:
    image: rmohr/activemq:5.14.3
    container_name: activemq-old
    networks:
      vulnnet:
        ipv4_address: 172.30.20.2
    ports:
      - 127.0.0.1:61616:61616
      - 127.0.0.1:8161:8161
  docker-registry-noauth:
    image: registry:2
    container_name: docker-registry
    networks:
      vulnnet:
        ipv4_address: 172.30.21.1
    ports:
      - 127.0.0.1:5000:5000

  express-old:
    image: node:6.14
    container_name: node-old
    networks:
      vulnnet:
        ipv4_address: 172.30.22.2
    command: tail -f /dev/null
    ports:
      - 127.0.0.1:3004:3000


  memcached-old:
    image: memcached:1.4
    container_name: memcached-old
    networks:
      vulnnet:
        ipv4_address: 172.30.25.1
    ports:
      - 127.0.0.1:11211:11211
  phpmyadmin-old:
    image: phpmyadmin/phpmyadmin:4.6
    container_name: phpmyadmin-old
    networks:
      vulnnet:
        ipv4_address: 172.30.26.1
    ports:
      - 127.0.0.1:8026:80
    environment:
    - PMA_HOST=mysql-old
  adminer:
    image: adminer:4.2
    container_name: adminer-old
    networks:
      vulnnet:
        ipv4_address: 172.30.26.2
    ports:
      - 127.0.0.1:8027:8080


  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    networks:
      vulnnet:
        ipv4_address: 172.30.28.1
    ports:
      - 127.0.0.1:5060:5060/udp
      - 127.0.0.1:10000-10010:10000-10010/udp
  openldap:
    image: osixia/openldap:1.2.0
    container_name: openldap
    networks:
      vulnnet:
        ipv4_address: 172.30.29.1
    ports:
      - 127.0.0.1:3891:389
      - 127.0.0.1:6361:636
    environment:
    - LDAP_ORGANISATION=VulnLab
    - LDAP_DOMAIN=vulnlab.local
    - LDAP_ADMIN_PASSWORD=admin
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    container_name: phpldapadmin
    networks:
      vulnnet:
        ipv4_address: 172.30.29.2
    ports:
      - 127.0.0.1:8030:80
    environment:
    - PHPLDAPADMIN_LDAP_HOSTS=openldap
  snmpd:
    image: polinux/snmpd
    container_name: snmpd
    networks:
      vulnnet:
        ipv4_address: 172.30.30.1
    ports:
      - 127.0.0.1:1611:161/udp
  owncloud-old:
    image: owncloud:9.1
    container_name: owncloud-old
    networks:
      vulnnet:
        ipv4_address: 172.30.31.1
    ports:
      - 127.0.0.1:8031:80

  mediawiki-old:
    image: mediawiki:1.27
    container_name: mediawiki-old
    networks:
      vulnnet:
        ipv4_address: 172.30.32.1
    ports:
      - 127.0.0.1:8033:80
  dokuwiki:
    image: mprasil/dokuwiki
    container_name: dokuwiki
    networks:
      vulnnet:
        ipv4_address: 172.30.32.2
    ports:
      - 127.0.0.1:8034:80




  wackopicko:
    image: adamdoupe/wackopicko
    container_name: wackopicko
    networks:
      vulnnet:
        ipv4_address: 172.30.39.1
    ports:
      - 127.0.0.1:8040:80










  tomcat7-vuln:
    image: tomcat:7.0.94
    container_name: tomcat7-vuln
    networks:
      vulnnet:
        ipv4_address: 172.30.44.1
    ports:
      - 127.0.0.1:8046:8080
  tomcat-ghostcat:
    image: vulhub/tomcat:9.0.30
    container_name: tomcat-ghostcat
    networks:
      vulnnet:
        ipv4_address: 172.30.44.2
    ports:
      - 127.0.0.1:8047:8080
      - 127.0.0.1:8009:8009
  solr-old:
    image: solr:6.6
    container_name: solr-old
    networks:
      vulnnet:
        ipv4_address: 172.30.45.1
    ports:
      - 127.0.0.1:8983:8983
  zookeeper-old:
    image: zookeeper:3.4
    container_name: zookeeper-old
    networks:
      vulnnet:
        ipv4_address: 172.30.46.1
    ports:
      - 127.0.0.1:2181:2181
  kafka-old:
    image: wurstmeister/kafka:2.11-0.10.2.2
    container_name: kafka-old
    depends_on:
    - zookeeper-old
    networks:
      vulnnet:
        ipv4_address: 172.30.47.1
    ports:
      - 127.0.0.1:9092:9092
    environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper-old:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.30.47.1:9092
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
  consul-old:
    image: consul:0.9.0
    container_name: consul-old
    networks:
      vulnnet:
        ipv4_address: 172.30.48.1
    ports:
      - 127.0.0.1:8500:8500
      - 127.0.0.1:8600:8600/udp
  vault-old:
    image: vault:0.9.0
    container_name: vault-old
    networks:
      vulnnet:
        ipv4_address: 172.30.49.1
    ports:
      - 127.0.0.1:8200:8200
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=myroot
    - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
    - IPC_LOCK
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    networks:
      vulnnet:
        ipv4_address: 172.30.50.1
    ports:
      - 127.0.0.1:8048:80
  echo-server:
    image: jmalloc/echo-server
    container_name: echo-server
    networks:
      vulnnet:
        ipv4_address: 172.30.50.3
    ports:
      - 127.0.0.1:8050:8080
  ubuntu14:
    container_name: ubuntu14
    image: ubuntu:14.04
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.1
  ubuntu16:
    container_name: ubuntu16
    image: ubuntu:16.04
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.2
  debian8:
    container_name: debian8
    image: debian:jessie
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.3
  debian9:
    container_name: debian9
    image: debian:stretch
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.4
  centos6:
    container_name: centos6
    image: centos:6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.5
  centos7:
    container_name: centos7
    image: centos:7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.6
  alpine37:
    container_name: alpine37
    image: alpine:3.7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.7
  fedora28:
    container_name: fedora28
    image: fedora:28
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.8
  apache22:
    ports:
      - 127.0.0.1:8150:80
    container_name: apache22
    image: httpd:2.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.9
  apache246:
    ports:
      - 127.0.0.1:8051:80
    container_name: apache246
    image: httpd:2.4.25
    networks:
      vulnnet:
        ipv4_address: 172.31.1.10
  nginx110:
    ports:
      - 127.0.0.1:8152:80
    container_name: nginx110
    image: nginx:1.10
    networks:
      vulnnet:
        ipv4_address: 172.31.1.11
  nginx112:
    ports:
      - 127.0.0.1:8153:80
    container_name: nginx112
    image: nginx:1.12
    networks:
      vulnnet:
        ipv4_address: 172.31.1.12
  nginx114:
    ports:
      - 127.0.0.1:8154:80
    container_name: nginx114
    image: nginx:1.14
    networks:
      vulnnet:
        ipv4_address: 172.31.1.13
  caddy20:
    ports:
      - 127.0.0.1:8155:80
    container_name: caddy20
    image: caddy:2.0.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.15
  tomcat6:
    ports:
      - 127.0.0.1:8060:8080
    container_name: tomcat6
    image: tomcat:6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.16
  tomcat7:
    ports:
      - 127.0.0.1:8061:8080
    container_name: tomcat7
    image: tomcat:7.0.70
    networks:
      vulnnet:
        ipv4_address: 172.31.1.17
  tomcat8:
    ports:
      - 127.0.0.1:8062:8080
    container_name: tomcat8
    image: tomcat:8.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.18

  jboss7:
    ports:
      - 127.0.0.1:8064:8080
    container_name: jboss7
    image: jboss/wildfly:8.2.1.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.20
  wildfly9:
    ports:
      - 127.0.0.1:8065:8080
    container_name: wildfly9
    image: jboss/wildfly:9.0.2.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.21
  wildfly10:
    ports:
      - 127.0.0.1:8066:8080
    container_name: wildfly10
    image: jboss/wildfly:10.1.0.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.22
  glassfish41:
    ports:
      - 127.0.0.1:8067:8080
      - 127.0.0.1:4848:4848
    container_name: glassfish41
    image: glassfish:4.1
    networks:
      vulnnet:
        ipv4_address: 172.31.1.24
  mysql55:
    ports:
      - 127.0.0.1:33062:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mysql55
    image: mysql:5.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.25
  mysql56:
    ports:
      - 127.0.0.1:33063:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mysql56
    image: mysql:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.26
  mariadb10:
    ports:
      - 127.0.0.1:33064:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mariadb10
    image: mariadb:10.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.27
  pg93:
    ports:
      - 127.0.0.1:54322:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    container_name: pg93
    image: postgres:9.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.28
  pg95:
    ports:
      - 127.0.0.1:54323:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    container_name: pg95
    image: postgres:9.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.29
  mongo32:
    ports:
      - 127.0.0.1:27018:27017
    container_name: mongo32
    image: mongo:3.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.30
  mongo36:
    ports:
      - 127.0.0.1:27019:27017
    container_name: mongo36
    image: mongo:3.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.31
  redis32:
    ports:
      - 127.0.0.1:6380:6379
    container_name: redis32
    image: redis:3.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.32
  redis50:
    ports:
      - 127.0.0.1:6381:6379
    container_name: redis50
    image: redis:5.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.33
  cassandra22:
    ports:
      - 127.0.0.1:9043:9042
    container_name: cassandra22
    image: cassandra:2.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.34
  couchdb16:
    ports:
      - 127.0.0.1:5985:5984
    container_name: couchdb16
    image: couchdb:1.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.35
  python27:
    container_name: python27
    image: python:2.7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.36
  python35:
    container_name: python35
    image: python:3.5
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.37
  python36:
    container_name: python36
    image: python:3.6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.38
  node6:
    container_name: node6
    image: node:6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.39
  node8:
    container_name: node8
    image: node:8
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.40
  node10:
    container_name: node10
    image: node:10
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.41
  ruby23:
    container_name: ruby23
    image: ruby:2.3
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.42
  ruby24:
    container_name: ruby24
    image: ruby:2.4
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.43
  php56:
    ports:
      - 127.0.0.1:8070:80
    container_name: php56
    image: php:5.6-apache
    networks:
      vulnnet:
        ipv4_address: 172.31.1.44
  php70:
    ports:
      - 127.0.0.1:8071:80
    container_name: php70
    image: php:7.0-apache
    networks:
      vulnnet:
        ipv4_address: 172.31.1.45
  go19:
    container_name: go19
    image: golang:1.9
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.46

  jenkins260:
    ports:
      - 127.0.0.1:8079:8080
    container_name: jenkins260
    image: jenkins/jenkins:2.60
    networks:
      vulnnet:
        ipv4_address: 172.31.1.48
  jenkins2150:
    ports:
      - 127.0.0.1:8081:8080
    container_name: jenkins2150
    image: jenkins/jenkins:2.150
    networks:
      vulnnet:
        ipv4_address: 172.31.1.49
  nexus2:
    ports:
      - 127.0.0.1:8082:8081
    container_name: nexus2
    image: sonatype/nexus:2.14.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.50

  sonar67:
    ports:
      - 127.0.0.1:9001:9000
    container_name: sonar67
    image: sonarqube:6.7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.52
  sonar70:
    ports:
      - 127.0.0.1:9002:9000
    container_name: sonar70
    image: sonarqube:7.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.53
  artifactory5:
    ports:
      - 127.0.0.1:8084:8081
    container_name: artifactory5
    image: docker.bintray.io/jfrog/artifactory-oss:5.11.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.54
  gitlab10:
    ports:
      - 127.0.0.1:8085:80
    container_name: gitlab10
    image: gitlab/gitlab-ce:10.0.0-ce.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.55
  gogs011:
    ports:
      - 127.0.0.1:3002:3000
    container_name: gogs011
    image: gogs/gogs:0.11
    networks:
      vulnnet:
        ipv4_address: 172.31.1.56
  gitea14:
    ports:
      - 127.0.0.1:3010:3000
    container_name: gitea14
    image: gitea/gitea:1.4.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.57
  rabbit36:
    ports:
      - 127.0.0.1:5673:5672
      - 127.0.0.1:15673:15672
    container_name: rabbit36
    image: rabbitmq:3.6-management
    networks:
      vulnnet:
        ipv4_address: 172.31.1.58
  rabbit37:
    ports:
      - 127.0.0.1:5674:5672
      - 127.0.0.1:15674:15672
    container_name: rabbit37
    image: rabbitmq:3.7-management
    networks:
      vulnnet:
        ipv4_address: 172.31.1.59
  kafka011:
    ports:
      - 127.0.0.1:9093:9092
    container_name: kafka011
    image: wurstmeister/kafka:2.11-0.11.0.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.60
  activemq514:
    ports:
      - 127.0.0.1:61617:61616
      - 127.0.0.1:8162:8161
    container_name: activemq514
    image: rmohr/activemq:5.14.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.61


  es24:
    ports:
      - 127.0.0.1:9201:9200
    container_name: es24
    image: elasticsearch:2.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.64
  es56:
    ports:
      - 127.0.0.1:9202:9200
    container_name: es56
    image: elasticsearch:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.65

  kibana46:
    ports:
      - 127.0.0.1:5602:5601
    container_name: kibana46
    image: kibana:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.67
  kibana56:
    ports:
      - 127.0.0.1:5603:5601
    container_name: kibana56
    image: kibana:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.68
  logstash56:
    ports:
      - 127.0.0.1:5045:5044
    container_name: logstash56
    image: logstash:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.69


  influx13:
    ports:
      - 127.0.0.1:8087:8086
    container_name: influx13
    image: influxdb:1.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.73
  nagios:
    ports:
      - 127.0.0.1:8088:80
    container_name: nagios
    image: jasonrivers/nagios
    networks:
      vulnnet:
        ipv4_address: 172.31.1.74
  zabbix40:
    ports:
      - 127.0.0.1:10052:10051
    container_name: zabbix40
    image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
    networks:
      vulnnet:
        ipv4_address: 172.31.1.75
  haproxy15:
    ports:
      - 127.0.0.1:8090:80
    container_name: haproxy15
    image: haproxy:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.76
  haproxy16:
    ports:
      - 127.0.0.1:8091:80
    container_name: haproxy16
    image: haproxy:1.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.77
  haproxy17:
    ports:
      - 127.0.0.1:8092:80
    container_name: haproxy17
    image: haproxy:1.7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.78
  squid35:
    ports:
      - 127.0.0.1:3129:3128
    container_name: squid35
    image: sameersbn/squid:3.5.27-2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.79
  traefik15:
    ports:
      - 127.0.0.1:8093:80
    container_name: traefik15
    image: traefik:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.80

  wp46:
    ports:
      - 127.0.0.1:8095:80
    container_name: wp46
    image: wordpress:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.82
  wp49:
    ports:
      - 127.0.0.1:8096:80
    container_name: wp49
    image: wordpress:4.9
    networks:
      vulnnet:
        ipv4_address: 172.31.1.83
  drupal7:
    ports:
      - 127.0.0.1:8097:80
    container_name: drupal7
    image: drupal:7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.84
  drupal85:
    ports:
      - 127.0.0.1:8098:80
    container_name: drupal85
    image: drupal:8.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.85
  joomla38:
    ports:
      - 127.0.0.1:8099:80
    container_name: joomla38
    image: joomla:3.8
    networks:
      vulnnet:
        ipv4_address: 172.31.1.86

  pma46:
    ports:
      - 127.0.0.1:8101:80
    container_name: pma46
    image: phpmyadmin/phpmyadmin:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.88
  pma48:
    ports:
      - 127.0.0.1:8102:80
    container_name: pma48
    image: phpmyadmin/phpmyadmin:4.8
    networks:
      vulnnet:
        ipv4_address: 172.31.1.89
  adminer42:
    ports:
      - 127.0.0.1:8103:8080
    container_name: adminer42
    image: adminer:4.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.90

  owncloud9:
    ports:
      - 127.0.0.1:8105:80
    container_name: owncloud9
    image: owncloud:9
    networks:
      vulnnet:
        ipv4_address: 172.31.1.92
  nextcloud12:
    ports:
      - 127.0.0.1:8106:80
    container_name: nextcloud12
    image: nextcloud:12
    networks:
      vulnnet:
        ipv4_address: 172.31.1.93
  mediawiki128:
    ports:
      - 127.0.0.1:8107:80
    container_name: mediawiki128
    image: mediawiki:1.28
    networks:
      vulnnet:
        ipv4_address: 172.31.1.94
  redmine33:
    ports:
      - 127.0.0.1:3006:3000
    container_name: redmine33
    image: redmine:3.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.95
  openssh:
    ports:
    - '127.0.0.1:2224:22'
    container_name: openssh
    image: linuxserver/openssh-server
    networks:
      vulnnet:
        ipv4_address: 172.31.1.96
  vsftpd:
    ports:
    - '127.0.0.1:2123:21'
    container_name: vsftpd
    image: fauria/vsftpd
    networks:
      vulnnet:
        ipv4_address: 172.31.1.97


  dovecot:
    ports:
      - 127.0.0.1:1431:143
    container_name: dovecot
    image: dovecot/dovecot
    networks:
      vulnnet:
        ipv4_address: 172.31.1.100
  bind:
    ports:
      - 127.0.0.1:5354:53/udp
    container_name: bind
    image: sameersbn/bind:9.11.3-20190706
    networks:
      vulnnet:
        ipv4_address: 172.31.1.101
  memcached14:
    ports:
      - 127.0.0.1:11212:11211
    container_name: memcached14
    image: memcached:1.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.102
  memcached15:
    ports:
      - 127.0.0.1:11213:11211
    container_name: memcached15
    image: memcached:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.103
  dvna:
    ports:
      - 127.0.0.1:9094:9090
    container_name: dvna
    image: appsecco/dvna
    networks:
      vulnnet:
        ipv4_address: 172.31.1.104

  ssrflab:
    ports:
      - 127.0.0.1:8109:80
    container_name: ssrflab
    image: youyouorz/ssrf-vulnerable-lab
    networks:
      vulnnet:
        ipv4_address: 172.31.1.106
  sqli:
    ports:
      - 127.0.0.1:8110:80
    container_name: sqli
    image: acgpiano/sqli-labs
    networks:
      vulnnet:
        ipv4_address: 172.31.1.107


  prometheus-old:
    ports:
      - 127.0.0.1:9091:9090
    container_name: prometheus-old
    image: prom/prometheus:v2.15.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.72

  metasploitable3:
    image: kirscht/metasploitable3-ub1404
    container_name: metasploitable3
    # This image uses an entrypoint script to start services.
    # Enable services by setting environment variables to "yes".
    # See https://hub.docker.com/r/kirscht/metasploitable3-ub1404
    # Starting a minimal set of services.
    environment:
      PASS: msfadmin
      SSH: "yes"
      FTP: "yes"
      SMB: "yes"
      HTTP: "yes"
    networks:
      vulnnet:
        ipv4_address: 172.30.1.3
    # The entrypoint seems to be part of the image, but it's not starting without it.
    # Based on the user-provided info, this is needed.
    entrypoint: /entrypoint.sh
    tty: true
    stdin_open: true

  dsvw:
    image: appsecco/dsvw
    container_name: dsvw
    networks:
      vulnnet:
        ipv4_address: 172.30.40.1
    ports:
      - "127.0.0.1:8008:8000"

  phpldapadmin-remote-dump:
    image: vulnerables/phpldapadmin-remote-dump
    container_name: phpldapadmin-remote-dump
    networks:
      vulnnet:
        ipv4_address: 172.30.40.5
    ports:
      - "127.0.0.1:8094:80"

  metasploit-emulator:
    image: vulnerables/metasploit-vulnerability-emulator
    container_name: metasploit-emulator
    networks:
      vulnnet:
        ipv4_address: 172.30.40.6
    ports:
      - "127.0.0.1:8100:80"

  shellshock-lab:
    image: vulnerables/cve-2014-6271
    container_name: shellshock-lab
    networks:
      vulnnet:
        ipv4_address: 172.30.40.7
    ports:
      - "127.0.0.1:8104:80"

  heartbleed-lab:
    image: vulnerables/cve-2014-0160
    container_name: heartbleed-lab
    networks:
      vulnnet:
        ipv4_address: 172.30.40.8
    ports:
      - "127.0.0.1:8105:443"

  xvwa:
    image: marcositu/xvwa2020
    container_name: xvwa
    networks:
      vulnnet:
        ipv4_address: 172.30.40.9
    ports:
      - "127.0.0.1:8108:80"

  railsgoat-alt:
    image: vulnerables/web-owasp-railsgoat
    container_name: railsgoat-alt
    networks:
      vulnnet:
        ipv4_address: 172.30.8.5
    ports:
      - "127.0.0.1:3007:80"

  bwapp-alt:
    image: hackersploit/bwapp-docker
    container_name: bwapp-alt
    networks:
      vulnnet:
        ipv4_address: 172.30.9.4
    ports:
      - "127.0.0.1:8111:80"

  metasploitable3-alt:
    image: heywoodlh/vulnerable
    container_name: metasploitable3-alt
    networks:
      vulnnet:
        ipv4_address: 172.30.1.4
    ports:
      - "127.0.0.1:2124:21"
      - "127.0.0.1:2225:22"
      - "127.0.0.1:8112:80"
      - "127.0.0.1:1392:139"
      - "127.0.0.1:4452:445"
      - "127.0.0.1:3307:3306"
    tty: true
    stdin_open: true