version: '3.8'
networks:
  vulnnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/16
services:
  ubuntu14:
    container_name: ubuntu14
    image: ubuntu:14.04
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.1
  ubuntu16:
    container_name: ubuntu16
    image: ubuntu:16.04
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.2
  debian8:
    container_name: debian8
    image: debian:jessie
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.3
  debian9:
    container_name: debian9
    image: debian:stretch
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.4
  centos6:
    container_name: centos6
    image: centos:6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.5
  centos7:
    container_name: centos7
    image: centos:7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.6
  alpine37:
    container_name: alpine37
    image: alpine:3.7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.7
  fedora28:
    container_name: fedora28
    image: fedora:28
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.8
  apache22:
    ports:
    - 8050:80
    container_name: apache22
    image: httpd:2.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.9
  apache246:
    ports:
    - 8051:80
    container_name: apache246
    image: httpd:2.4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.10
  nginx110:
    ports:
    - 8052:80
    container_name: nginx110
    image: nginx:1.10
    networks:
      vulnnet:
        ipv4_address: 172.31.1.11
  nginx112:
    ports:
    - 8053:80
    container_name: nginx112
    image: nginx:1.12
    networks:
      vulnnet:
        ipv4_address: 172.31.1.12
  nginx114:
    ports:
    - 8054:80
    container_name: nginx114
    image: nginx:1.14
    networks:
      vulnnet:
        ipv4_address: 172.31.1.13
  lighttpd:
    ports:
    - 8055:80
    container_name: lighttpd
    image: sebp/lighttpd
    networks:
      vulnnet:
        ipv4_address: 172.31.1.14
  caddy1:
    ports:
    - 8056:80
    container_name: caddy1
    image: caddy:1.0.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.15
  tomcat6:
    ports:
    - 8060:8080
    container_name: tomcat6
    image: tomcat:6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.16
  tomcat7:
    ports:
    - 8061:8080
    container_name: tomcat7
    image: tomcat:7.0.70
    networks:
      vulnnet:
        ipv4_address: 172.31.1.17
  tomcat8:
    ports:
    - 8062:8080
    container_name: tomcat8
    image: tomcat:8.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.18
  tomcat850:
    ports:
    - 8063:8080
    container_name: tomcat850
    image: tomcat:8.5.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.19
  jboss7:
    ports:
    - 8064:8080
    container_name: jboss7
    image: jboss/wildfly:8.2.1.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.20
  wildfly9:
    ports:
    - 8065:8080
    container_name: wildfly9
    image: jboss/wildfly:9.0.2.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.21
  wildfly10:
    ports:
    - 8066:8080
    container_name: wildfly10
    image: jboss/wildfly:10.1.0.Final
    networks:
      vulnnet:
        ipv4_address: 172.31.1.22
  jetty92:
    ports:
    - 8067:8080
    container_name: jetty92
    image: jetty:9.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.23
  glassfish4:
    ports:
    - 8068:8080
    container_name: glassfish4
    image: glassfish:4.1
    networks:
      vulnnet:
        ipv4_address: 172.31.1.24
  mysql55:
    ports:
    - 33062:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mysql55
    image: mysql:5.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.25
  mysql56:
    ports:
    - 33063:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mysql56
    image: mysql:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.26
  mariadb10:
    ports:
    - 33064:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    container_name: mariadb10
    image: mariadb:10.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.27
  pg93:
    ports:
    - 54322:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    container_name: pg93
    image: postgres:9.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.28
  pg95:
    ports:
    - 54323:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    container_name: pg95
    image: postgres:9.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.29
  mongo32:
    ports:
    - 27018:27017
    container_name: mongo32
    image: mongo:3.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.30
  mongo36:
    ports:
    - 27019:27017
    container_name: mongo36
    image: mongo:3.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.31
  redis32:
    ports:
    - 6380:6379
    container_name: redis32
    image: redis:3.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.32
  redis50:
    ports:
    - 6381:6379
    container_name: redis50
    image: redis:5.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.33
  cassandra22:
    ports:
    - 9043:9042
    container_name: cassandra22
    image: cassandra:2.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.34
  couchdb16:
    ports:
    - 5985:5984
    container_name: couchdb16
    image: couchdb:1.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.35
  python27:
    container_name: python27
    image: python:2.7
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.36
  python35:
    container_name: python35
    image: python:3.5
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.37
  python36:
    container_name: python36
    image: python:3.6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.38
  node6:
    container_name: node6
    image: node:6
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.39
  node8:
    container_name: node8
    image: node:8
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.40
  node10:
    container_name: node10
    image: node:10
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.41
  ruby23:
    container_name: ruby23
    image: ruby:2.3
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.42
  ruby24:
    container_name: ruby24
    image: ruby:2.4
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.43
  php56:
    ports:
    - 8070:80
    container_name: php56
    image: php:5.6-apache
    networks:
      vulnnet:
        ipv4_address: 172.31.1.44
  php70:
    ports:
    - 8071:80
    container_name: php70
    image: php:7.0-apache
    networks:
      vulnnet:
        ipv4_address: 172.31.1.45
  go19:
    container_name: go19
    image: golang:1.9
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.46
  jdk8:
    container_name: jdk8
    image: openjdk:8
    command: tail -f /dev/null
    networks:
      vulnnet:
        ipv4_address: 172.31.1.47
  jenkins260:
    ports:
    - 8080:8080
    container_name: jenkins260
    image: jenkins/jenkins:2.60
    networks:
      vulnnet:
        ipv4_address: 172.31.1.48
  jenkins2150:
    ports:
    - 8081:8080
    container_name: jenkins2150
    image: jenkins/jenkins:2.150
    networks:
      vulnnet:
        ipv4_address: 172.31.1.49
  nexus2:
    ports:
    - 8082:8081
    container_name: nexus2
    image: sonatype/nexus:2.14.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.50
  nexus3:
    ports:
    - 8083:8081
    container_name: nexus3
    image: sonatype/nexus3:3.0.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.51
  sonar67:
    ports:
    - 9001:9000
    container_name: sonar67
    image: sonarqube:6.7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.52
  sonar70:
    ports:
    - 9002:9000
    container_name: sonar70
    image: sonarqube:7.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.53
  artifactory5:
    ports:
    - 8084:8081
    container_name: artifactory5
    image: docker.bintray.io/jfrog/artifactory-oss:5.11.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.54
  gitlab10:
    ports:
    - 8085:80
    container_name: gitlab10
    image: gitlab/gitlab-ce:10.0.0-ce.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.55
  gogs011:
    ports:
    - 3002:3000
    container_name: gogs011
    image: gogs/gogs:0.11
    networks:
      vulnnet:
        ipv4_address: 172.31.1.56
  gitea14:
    ports:
    - 3003:3000
    container_name: gitea14
    image: gitea/gitea:1.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.57
  rabbit36:
    ports:
    - 5673:5672
    - 15673:15672
    container_name: rabbit36
    image: rabbitmq:3.6-management
    networks:
      vulnnet:
        ipv4_address: 172.31.1.58
  rabbit37:
    ports:
    - 5674:5672
    - 15674:15672
    container_name: rabbit37
    image: rabbitmq:3.7-management
    networks:
      vulnnet:
        ipv4_address: 172.31.1.59
  kafka011:
    ports:
    - 9093:9092
    container_name: kafka011
    image: wurstmeister/kafka:2.11-0.11.0.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.60
  activemq514:
    ports:
    - 61617:61616
    - 8162:8161
    container_name: activemq514
    image: rmohr/activemq:5.14.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.61
  activemq515:
    ports:
    - 61618:61616
    - 8163:8161
    container_name: activemq515
    image: rmohr/activemq:5.15.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.62
  zeromq:
    ports:
    - 5556:5555
    container_name: zeromq
    image: zeromq/zeromq
    networks:
      vulnnet:
        ipv4_address: 172.31.1.63
  es24:
    ports:
    - 9201:9200
    container_name: es24
    image: elasticsearch:2.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.64
  es56:
    ports:
    - 9202:9200
    container_name: es56
    image: elasticsearch:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.65
  es60:
    ports:
    - 9203:9200
    container_name: es60
    image: elasticsearch:6.0.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.66
  kibana46:
    ports:
    - 5602:5601
    container_name: kibana46
    image: kibana:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.67
  kibana56:
    ports:
    - 5603:5601
    container_name: kibana56
    image: kibana:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.68
  logstash56:
    ports:
    - 5045:5044
    container_name: logstash56
    image: logstash:5.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.69
  grafana46:
    ports:
    - 3004:3000
    container_name: grafana46
    image: grafana/grafana:4.6.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.70
  grafana50:
    ports:
    - 3005:3000
    container_name: grafana50
    image: grafana/grafana:5.0.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.71
  prom18:
    ports:
    - 9091:9090
    container_name: prom18
    image: prom/prometheus:v1.8.0
    networks:
      vulnnet:
        ipv4_address: 172.31.1.72
  influx13:
    ports:
    - 8087:8086
    container_name: influx13
    image: influxdb:1.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.73
  nagios:
    ports:
    - 8088:80
    container_name: nagios
    image: jasonrivers/nagios
    networks:
      vulnnet:
        ipv4_address: 172.31.1.74
  zabbix40:
    ports:
    - 10052:10051
    container_name: zabbix40
    image: zabbix/zabbix-server-mysql:ubuntu-4.0-latest
    networks:
      vulnnet:
        ipv4_address: 172.31.1.75
  haproxy15:
    ports:
    - 8090:80
    container_name: haproxy15
    image: haproxy:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.76
  haproxy16:
    ports:
    - 8091:80
    container_name: haproxy16
    image: haproxy:1.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.77
  haproxy17:
    ports:
    - 8092:80
    container_name: haproxy17
    image: haproxy:1.7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.78
  squid35:
    ports:
    - 3129:3128
    container_name: squid35
    image: sameersbn/squid:3.5.27-2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.79
  traefik15:
    ports:
    - 8093:80
    container_name: traefik15
    image: traefik:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.80
  varnish41:
    ports:
    - 8094:80
    container_name: varnish41
    image: varnish:4.1
    networks:
      vulnnet:
        ipv4_address: 172.31.1.81
  wp46:
    ports:
    - 8095:80
    container_name: wp46
    image: wordpress:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.82
  wp49:
    ports:
    - 8096:80
    container_name: wp49
    image: wordpress:4.9
    networks:
      vulnnet:
        ipv4_address: 172.31.1.83
  drupal7:
    ports:
    - 8097:80
    container_name: drupal7
    image: drupal:7
    networks:
      vulnnet:
        ipv4_address: 172.31.1.84
  drupal85:
    ports:
    - 8098:80
    container_name: drupal85
    image: drupal:8.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.85
  joomla38:
    ports:
    - 8099:80
    container_name: joomla38
    image: joomla:3.8
    networks:
      vulnnet:
        ipv4_address: 172.31.1.86
  magento22:
    ports:
    - 8100:80
    container_name: magento22
    image: bitnami/magento:2.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.87
  pma46:
    ports:
    - 8101:80
    container_name: pma46
    image: phpmyadmin/phpmyadmin:4.6
    networks:
      vulnnet:
        ipv4_address: 172.31.1.88
  pma48:
    ports:
    - 8102:80
    container_name: pma48
    image: phpmyadmin/phpmyadmin:4.8
    networks:
      vulnnet:
        ipv4_address: 172.31.1.89
  adminer42:
    ports:
    - 8103:8080
    container_name: adminer42
    image: adminer:4.2
    networks:
      vulnnet:
        ipv4_address: 172.31.1.90
  roundcube12:
    ports:
    - 8104:80
    container_name: roundcube12
    image: roundcube/roundcubemail:1.2.x
    networks:
      vulnnet:
        ipv4_address: 172.31.1.91
  owncloud9:
    ports:
    - 8105:80
    container_name: owncloud9
    image: owncloud:9
    networks:
      vulnnet:
        ipv4_address: 172.31.1.92
  nextcloud12:
    ports:
    - 8106:80
    container_name: nextcloud12
    image: nextcloud:12
    networks:
      vulnnet:
        ipv4_address: 172.31.1.93
  mediawiki128:
    ports:
    - 8107:80
    container_name: mediawiki128
    image: mediawiki:1.28
    networks:
      vulnnet:
        ipv4_address: 172.31.1.94
  redmine33:
    ports:
    - 3006:3000
    container_name: redmine33
    image: redmine:3.3
    networks:
      vulnnet:
        ipv4_address: 172.31.1.95
  openssh:
    ports:
    - '2224:22'
    container_name: openssh
    image: linuxserver/openssh-server
    networks:
      vulnnet:
        ipv4_address: 172.31.1.96
  vsftpd:
    ports:
    - '2123:21'
    container_name: vsftpd
    image: fauria/vsftpd
    networks:
      vulnnet:
        ipv4_address: 172.31.1.97
  proftpd:
    ports:
    - '2124:21'
    container_name: proftpd
    image: hauptmedia/proftpd
    networks:
      vulnnet:
        ipv4_address: 172.31.1.98
  postfix:
    ports:
    - '2526:25'
    container_name: postfix
    image: catatnight/postfix
    networks:
      vulnnet:
        ipv4_address: 172.31.1.99
  dovecot:
    ports:
    - 1431:143
    container_name: dovecot
    image: dovecot/dovecot
    networks:
      vulnnet:
        ipv4_address: 172.31.1.100
  bind:
    ports:
    - 5354:53/udp
    container_name: bind
    image: sameersbn/bind:9.11.3-20190706
    networks:
      vulnnet:
        ipv4_address: 172.31.1.101
  memcached14:
    ports:
    - 11212:11211
    container_name: memcached14
    image: memcached:1.4
    networks:
      vulnnet:
        ipv4_address: 172.31.1.102
  memcached15:
    ports:
    - 11213:11211
    container_name: memcached15
    image: memcached:1.5
    networks:
      vulnnet:
        ipv4_address: 172.31.1.103
  dvna:
    ports:
    - 9094:9090
    container_name: dvna
    image: appsecco/dvna
    networks:
      vulnnet:
        ipv4_address: 172.31.1.104
  vulnlab:
    ports:
    - 8108:8080
    container_name: vulnlab
    image: dvja/dvja
    networks:
      vulnnet:
        ipv4_address: 172.31.1.105
  ssrflab:
    ports:
    - 8109:80
    container_name: ssrflab
    image: youyouorz/ssrf-vulnerable-lab
    networks:
      vulnnet:
        ipv4_address: 172.31.1.106
  sqli:
    ports:
    - 8110:80
    container_name: sqli
    image: acgpiano/sqli-labs
    networks:
      vulnnet:
        ipv4_address: 172.31.1.107
  xsslab:
    ports:
    - 8111:80
    container_name: xsslab
    image: vulnerables/xss-vulnerability-lab
    networks:
      vulnnet:
        ipv4_address: 172.31.1.108
  uploadlab:
    ports:
    - 8112:80
    container_name: uploadlab
    image: vulnerables/file-upload
    networks:
      vulnnet:
        ipv4_address: 172.31.1.109
  wavsep:
    ports:
    - 8113:8080
    container_name: wavsep
    image: yourselfscan/wavsep
    networks:
      vulnnet:
        ipv4_address: 172.31.1.110
